# Generated by Django 5.0.6 on 2024-09-07 00:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('jobType', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Permanent', max_length=40)),
                ('education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PHD', 'Phd')], default='Bachelors', max_length=40)),
                ('industry', models.CharField(choices=[('Information Technology', 'It'), ('Business', 'Business'), ('Banking', 'Banking'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Telecommunications', 'Telecommunications'), ('Others', 'Others')], default='Business', max_length=40)),
                ('experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Years', 'Two Year'), ('3 Years or above', 'Three Year Plus')], default='No Experience', max_length=40)),
                ('salary', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('positions', models.IntegerField(default=1, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('lastDate', models.DateField(default='2024-09-07')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
