# Generated by Django 5.0.6 on 2024-09-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lastDate',
            field=models.DateField(default='2024-09-19'),
        ),
    ]
